trigger: none
pr: none

parameters:
  - name: Location
    displayName: Select the location for Enabler Components Deployment
    type: string
    default: "UKS_Shared"
    values:
      - UKS_Shared
      - UKW_Shared
      - IN_Shared

  - name: DashboardType
    displayName: Select Dashboard Type
    type: string
    default: "Standard Dashboard"

  - name: exportJSON
    displayName: Export JSON
    type: boolean
    default: true
  - name: Dashboard_ID
    displayName: Enter Dashboard ID (only used if Export JSON is selected)
    type: string
    default: ''
